version: "3.9"
   
services:
  db:
    image: postgres
    container_name: shopbridge_db_server
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    container_name: shopbridge_web_server
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && daphne -b 0.0.0.0 -p 8000 shopbridge.asgi:application"
    volumes:
      - ./shopbridge:/code
      - static_volume:/code/staticfiles
    expose:
      - 8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  nginx:
    build: ./nginx
    container_name: shopbridge_ng_server
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume: